#插件的提示前缀
name: "&b[TrpServerTimeCommand]"

#每日在线时间清空的时间（请不要使用全角符号
endTime: "00:00"

#本项基于oneTime数据
timeTask:
#ID，请按照顺序命名
  1:
    #间隔时间/min
    time: 1
    #要执行的指令，%playerName%代表玩家名称,@no代表不执行
    command: "give %playerName% book 1"
    #发送给玩家的提示信息，%oneTimeMin%代表本次服务器启动后的在线时间单位为分钟
    message:  "&e你获得了一本书"

#本项基于dayTime数据
dayTimeTask:
  1:
    #间隔时间/min
    time: 1
    #要执行的指令，%playerName%代表玩家名称,@no代表不执行
    command: "give %playerName% book 1"
    #发送给玩家的提示信息，%dayTimeMin%代表每日在线时间单位为分钟
    message: "&e你获得了一本书"

#本项基于allTime数据
allTimeTask:
  1:
    #间隔时间/min
    time: 1
    #要执行的指令，%playerName%代表玩家名称,@no代表不执行
    command: "give %playerName% book 1"
    #发送给玩家的提示信息，%allTimeMin%代表总在线时间单位为分钟
    message: "&e你获得了一本书"

#本项基于dayTime数据
dayTimeEvent:
  1:
    #达成条件/min
    time: 1
    #要执行的指令，%playerName%代表玩家名称,@no代表不执行
    command: "give %playerName% book 1"
    #发送给玩家的提示信息，%allTimeMin%代表总在线时间单位为分钟
    message: "&e你获得了一本书"

#本项基于oneTime数据
oneTimeEvent:
  1:
    #达成条件/min
    time: 1
    #要执行的指令，%playerName%代表玩家名称,@no代表不执行
    command: "give %playerName% book 1"
    #发送给玩家的提示信息，%allTimeMin%代表总在线时间单位为分钟
    message: "&e你获得了一本书"

#本项基于allTime数据
allTimeEvent:
  1:
    #达成条件/min
    time: 1
    #要执行的指令，%playerName%代表玩家名称,@no代表不执行
    command: "give %playerName% book 1"
    #发送给玩家的提示信息，%allTimeMin%代表总在线时间单位为分钟
    message: "&e你获得了一本书"