main: TrpServerTimeCommand.Main
version: 1.2
name: TrpServerTimeCommand
api-version: 1.15
commands:
  TrpServerTimeCommand:
    aliases:
      - "stc"
    description: "check a player`s data"
    usage: "/stc <PlayerName>"